---
title: "Homework 9"
output: 
  html_notebook:
  toc: yes
  toc_float: yes
author: Wenlong Li
---

### 2.1-a
```{r}
library(dplyr)
rm(list=ls())

# Set working directory as needed
setwd("./")
df <- read.csv("products.csv",sep = ',',header = F)

canonical_conversion <- function(originFilePath, canonicalFilePath, df){
  tr_k <- file(originFilePath, "r")
  tr_k_canonical <- file(canonicalFilePath, "w")
  line=readLines(tr_k,n=1)
  while(length(line) != 0 ) {
    index = 1
    str <- ""
    for(item in unlist(strsplit(line,split = ","))){
      if(index > 1){
        splitStr = ""
        if(nchar(str)!=0){
          splitStr = ","
        }
        str <- paste0(str, splitStr, df[as.integer(item)+1,2])
      }
      index <- index+1
    }
    writeLines(text = str, con = tr_k_canonical)
    line=readLines(tr_k,n=1)
  }
  close(tr_k)
  close(tr_k_canonical)
}


tr_list <- c("tr-1k.csv","tr-5k.csv","tr-20k.csv", "tr-75k.csv");
tr_canonical_list <- c("tr-1k-canonical.csv","tr-5k-canonical.csv","tr-20k-canonical.csv", "tr-75k-canonical.csv");

for (item in 1:length(tr_list)) {
  canonical_conversion(tr_list[item], tr_canonical_list[item], df)
}
rm(df)
```
### 2.1-b
```{r}
library(arules)

# tr-1k-canonical.csv
print("excel tr-1k-canonical")
trans <- read.transactions("tr-1k-canonical.csv", sep=",")
f_is <- apriori(trans, parameter=list(support=0.025, target="frequent itemsets"))
inspect(sort(f_is, decreasing = T, by="count"))
rm(f_is)
rules <- apriori(trans, parameter = list(support=0.025, confidence=0.9))
inspect(sort(rules, decreasing = T, by="confidence"))
rm(rules)
rm(trans)

# tr-5k-canonical.csv
print("excel tr-5-canonical")
trans <- read.transactions("tr-5k-canonical.csv", sep=",")
f_is <- apriori(trans, parameter=list(support=0.025, target="frequent itemsets"))
inspect(sort(f_is, decreasing = T, by="count"))
rm(f_is)
rules <- apriori(trans, parameter = list(support=0.025, confidence=0.9))
inspect(sort(rules, decreasing = T, by="count"))
rm(rules)
rm(trans)

# tr-20k-canonical.csv
print("excel tr-20-canonical")
trans <- read.transactions("tr-20k-canonical.csv", sep=",")
f_is <- apriori(trans, parameter=list(support=0.025, target="frequent itemsets"))
inspect(sort(f_is, decreasing = T, by="count"))
rm(f_is)
rules <- apriori(trans, parameter = list(support=0.025, confidence=0.9))
inspect(sort(rules, decreasing = T, by="count"))
rm(rules)
rm(trans)

# tr-75k-canonical.csv
print("excel tr-75-canonical")
trans <- read.transactions("tr-75k-canonical.csv", sep=",")
f_is <- apriori(trans, parameter=list(support=0.025, target="frequent itemsets"))
inspect(sort(f_is, decreasing = T, by="count"))
rm(f_is)
rules <- apriori(trans, parameter = list(support=0.025, confidence=0.9))
inspect(sort(rules, decreasing = T, by="count"))
rm(rules)
rm(trans)
```
### 2.1-c
#### The greater the amount of transaction data, the more accurate the association rules mined, and the more practical meaning
### 2.1-d-i
#### Coffee Eclair
### 2.1-d-ii
#### {Apple Croissant, Apple Danish, Apple Tart}

### 2.2
```{r}
library(dplyr)
setwd("./")

user.id <- 20475195 %% 671

ratings.df <- read.csv('./ml-latest-small/ratings.csv')
movies.df <- read.csv('./ml-latest-small/movies.csv')

user.id.df <- filter(ratings.df, ratings.df$userId == user.id)

user.movieid.df <- filter(movies.df, movies.df$movieId %in% user.id.df$movieId)

genresList <- c("Action", "Adventure", "Animation", "Children", "Comedy", "Crime", "Documentary", "Drama", "Fantasy", "Film-Noir", "Horror", "IMAX", "Musical", "Mystery", "Romance", "Sci-Fi", "Thriller", "War", "Western", "(no genres listed)")

create_movie_profile <- function(df, genresList){
  result <- matrix(nrow = 0, ncol = 20)
  colnames(result) <- genresList
  names <- matrix(nrow = 0, ncol = 2)
  colnames(names) <- c("MovieId","MovieName")
  for (item in 1:nrow(df)) {
    genres <- df[item,"genres"]
    genresValue <- c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0)
    for(genre in unlist(strsplit(genres,split = '|',fixed= T))){
      genresValue[which(genresList == genre)] = 1
    }
    names <- rbind(names, c(df[item,"movieId"], df[item,"title"]))
    result <- rbind(result, as.integer(genresValue))
  }
  return(data.frame(names, result))
}

create_user_profile <- function(user.movieid.df, genresList){
  df <- create_movie_profile(user.movieid.df, genresList)
  y <- select(df, -MovieId, -MovieName)
  return(data.frame(t(colMeans(y))))
}

my_cosine <- function(x, y){
  cosine <- sum(x*y)/(norm(x, type = "2")*norm(y, type = "2"))
  return(cosine)
}

user.profile <- create_user_profile(user.movieid.df, genresList)

random.movies <- movies.df[sample(nrow(movies.df), 10), ]
random.movies <- create_movie_profile(random.movies, genresList)
random.movies$Similarity <- c(0.0)

for (row in 1:nrow(random.movies)) {
   movies.profile <- select(random.movies, -MovieId, -MovieName, -Similarity)[row,]
   random.movies[row,]$Similarity = my_cosine(movies.profile, user.profile)
}
random.movies <- random.movies[order(random.movies$Similarity, decreasing=TRUE),]

print(select(random.movies, MovieId, MovieName, Similarity)[1:5,])
rm(ratings.df)
rm(movies.df)
```

